version: '3.4'

services:
  pruebanodejs:
    image: pruebanodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - 3000:3000
