version: '3.4'

services:
  pruebanodejs:
    image: pruebanodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["ts-node-dev", "--inspect=0.0.0.0:9229", "index.js"]
